name: Build VATSIM Index

on: workflow_dispatch

permissions:
  contents: write

jobs:
  build_index:
    runs-on: "ubuntu-latest"
    container: "python:3.11.8"
    env:
      CI_COMMIT_MESSAGE: Continuous Integration Autobuild
      CI_COMMIT_AUTHOR: Continuous Integration
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          mkdir -p ~/.cache/pip
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Build indexes
        env:
          DATA_URL: https://raw.githubusercontent.com/vatsimnetwork/vatspy-data-project/master/Boundaries.geojson
        run: |
          python3.11 build_index.py -i ${DATA_URL} -o prebuilt/vatsim/vatsim4.idx -p 4 -t 10 -m
          python3.11 build_index.py -i ${DATA_URL} -o prebuilt/vatsim/vatsim5.idx -p 5 -t 10 -m
          python3.11 build_index.py -i ${DATA_URL} -o prebuilt/vatsim/vatsim6.idx -p 6 -t 20 -m
      - name: GIT Commit Artifacts
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"
          git add prebuilt
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}" && git push || true
